#inherit_from: .rubocop_todo.yml

Style/Encoding:
  Enabled: false
#
#ClassAndModuleChildren:
#  Enabled: false

Metrics/LineLength:
  Max: 150

Documentation:
    Enabled: false

AllCops:
  Exclude:
    - db/**
    - bin/**
    - lib/**

